Mousetrap.bind("m", () => {
    buyCurrency(15, "x")
    buybtn(16)
    buybtn(25)
    buybtn(24)
    buybtn(14)
    buybtn(13)
    buybtn(23)
    buyCurrency(26, "y")
    buybtn(27)
    buybtn(17)
    buybtn(35)
    buybtn(45)
    buybtn(44)
    buybtn(34)
    buybtn(33)
    buybtn(43)
    buybtn(53)
    buybtn(36)
    buybtn(46)
    buyCurrency(55, "z")
    buybtn(37)
    buybtn(47)
    buybtn(56)
    buybtn(57)
})

Mousetrap.bind("r", () => {
    if (game.inTrial == 0) rebirth()
    else completeTrial()
})